services:
  - type: web
    name: my-backend
    env: node
    plan: free
    buildCommand: |
      npm install
      npx hardhat compile
    startCommand: npm start
    envVars:
      - key: APP_ENV
        value: production
